routes/web.php
<?php
use App\Http\Controllers\Admin\CategoryController;
use App\Http\Controllers\Admin\CouponController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\ProductController;
use App\Http\Controllers\Client\ProductController as ClientProductController;
use App\Http\Controllers\Admin\RoleController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Client\CartController;
use App\Http\Controllers\Client\HomeController;
use App\Http\Controllers\Client\OrderController;
use App\Http\Controllers\Admin\OrderController as AdminOrderController;
use App\Http\Controllers\Client\ProfileController;
use Illuminate\Support\Facades\Route;
use Symfony\Component\HttpKernel\Profiler\Profile;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider and all of them will
| be assigned to the "web" middleware group. Make something great!
|
*/
//Request $request,$categoryID
Route::get('/', [HomeController::class, 'index'])->name('client.home');

Route::get('product/{category_id}', [ClientProductController::class, 'index'])->name('client.products.index');
Route::get('product-detail/{id}', [ClientProductController::class, 'show'])->name('client.products.show');

Route::middleware('auth')->group(function(){
    Route::post('add-to-cart', [CartController::class, 'store'])->name('client.cart.add');
    Route::get('carts', [CartController::class, 'index'])->name('client.cart.index');
    Route::post('update-quantity-product-in-cart/{cart_product_id}', [CartController::class, 'updateQuantityProduct'])->name('client.carts.update_product_quantity');
    Route::post('remove-product-in-cart/{cart_product_id}', [CartController::class, 'removeProductInCart'])->name('client.carts.remove_product');
    Route::post('apply-coupon', [CartController::class, 'applyCoupon'])->name('client.carts.apply_coupon');
    Route::get('checkout', [CartController::class, 'checkout'])->name('client.checkout.index')->middleware('user.can_checkout_cart');
    Route::post('process-checkout', [CartController::class, 'processCheckout'])->name('client.checkout.process')->middleware('user.can_checkout_cart');
    Route::get('list-orders', [OrderController::class, 'index'])->name('client.orders.index');
    Route::post('orders/cancel/{id}', [OrderController::class, 'cancel'])->name('client.orders.cancel');
    Route::get('products/search', [ClientProductController::class, 'searchByName'])->name('client.products.search');
    Route::get('home/search', [HomeController::class, 'search'])->name('client.home.search');
    Route::get('home/account', [ProfileController::class, 'showAccount'])->name('client.home.account');
    Route::get('account/view-update-profile', [ProfileController::class, 'viewUpdateProfile'])->name('client.view.profile.update');
    Route::put('account/update-profile', [ProfileController::class, 'UpdateProfile'])->name('client.profile.update');
    
//->middleware('user.can_checkout_cart');
});

Auth::routes();



// Route::middleware('auth')->group(function(){
//     Route::get('/dashboard',[DashboardController::class,'index'])-> name('dashboard')->middleware('can:show-dashboard');
Route::middleware(['auth', 'can:show-dashboard'])->group(function () {
        Route::get('/dashboard', [DashboardController::class, 'index'])->name('dashboard');

        
    Route::prefix('roles')->controller(RoleController::class)->name('roles.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('role:super-admin');
        Route::post('/', 'store')->name('store')->middleware('role:super-admin');
        Route::get('/create', 'create')->name('create')->middleware('role:super-admin');
        Route::get('/{coupon}', 'show')->name('show')->middleware('role:super-admin');
        Route::put('/{coupon}', 'update')->name('update')->middleware('role:super-admin');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('role:super-admin');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('role:super-admin');
    });
    // Route::resource('users', UserController::class);
    Route::prefix('users')->controller(UserController::class)->name('users.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-user');
        Route::post('/', 'store')->name('store');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-user');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-user');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-user');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-user');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-user');
    });
    // Route::resource('categories', CategoryController::class);
    Route::prefix('categories')->controller(CategoryController::class)->name('categories.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-category');
        Route::post('/', 'store')->name('store')->middleware('permission:create-category');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-category');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-category');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-category');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-category');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-category');
    });

    // Route::resource('products', ProductController::class);

    Route::prefix('products')->controller(ProductController::class)->name('products.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-product');
        Route::post('/', 'store')->name('store')->middleware('permission:create-product');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-product');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-product');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-product');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-product');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-product');
    });

    //Route::resource     ('coupons', CouponController::class);

    Route::prefix('coupons')->controller(CouponController::class)->name('coupons.')->group(function(){
        Route::get('/', 'index')->name('index')->middleware('permission:show-coupon');
        Route::post('/', 'store')->name('store')->middleware('permission:create-coupon');
        Route::get('/create', 'create')->name('create')->middleware('permission:create-coupon');
        Route::get('/{coupon}', 'show')->name('show')->middleware('permission:show-coupon');
        Route::put('/{coupon}', 'update')->name('update')->middleware('permission:update-coupon');
        Route::delete('/{coupon}', 'destroy')->name('destroy')->middleware('permission:delete-coupon');
        Route::get('/{coupon}/edit', 'edit')->name('edit')->middleware('permission:update-coupon');
});

    
        Route::get('orders', [AdminOrderController::class, 'index'])->name('admin.orders.index')->middleware('permission:list-order');
        Route::post('update-status/{id}', [AdminOrderController::class, 'updateStatus'])->name('admin.orders.update_status')->middleware('permission:update-order-status');
        Route::get('admin/orders/{id}/print', [AdminOrderController::class, 'print'])->name('admin.orders.print');


});

app/Models/Cart.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Cart extends Model
{
    use HasFactory;

    protected $fillable = [
        'user_id',
    ];

    public function products()
    {
        return $this->hasMany(CartProduct::class, 'cart_id');
    }

    public function getBy($userId)
    {
        return Cart::whereUserId($userId)->first();
    }

    public function firstOrCreateBy($userId)
    {
        $cart = $this->getBy($userId);

        if (!$cart) {
            $cart = $this->create(['user_id' => $userId]);
        }
        return $cart;
    }


    public function getProductCountAttribute()
    {
        return auth()->check() ? $this->products->count() : 0;
    }

    public function getTotalPriceAttribute()
    {
        return auth()->check() ? $this->products->reduce(function ($carry, $item) {
            $item->load('product');
            $price = $item->product_quantity * ($item->product->sale ? $item->product->sale_price : $item->product->price);
            return $carry + $price;
        }, 0) : 0;
    }
}

app/Models/Product.php
<?php

namespace App\Models;

use App\Traits\HandleImageTrait;
use App\Traits\Imaginable;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Product extends Model
{
    use HasFactory, HandleImageTrait;
    protected $fillable = [
        'name',
        'description',
        'sale',
        'price'
    ];

    public function details()
    {
        return $this->hasMany(ProductDetail::class);
    }
    public function images()
    {
        return $this->morphMany(Image::class, 'imageable');
    }
    public function categories()
    {
        return $this->belongsToMany(Category::class);
    }

    public function orders()
    {
        return $this->belongsToMany(Order::class, 'product_orders')
            ->withPivot('product_size', 'product_quantity', 'product_price')
            ->withTimestamps();
    }

    public function assignCategory($categoryIds)
    {
        return $this->categories()->sync($categoryIds);
    }
    // public function assignDetail($categoryIds){
    //     return $this->categories()->sync($categoryIds);
    // }

    public function getBy($dataSearch, $categoryId)
    {
        return $this->whereHas('categories', fn($q) => $q->where('category_id', $categoryId))->paginate(9);
    }
    
    public function getImagePathAttribute()
    {
        return asset($this->images->count() > 0 ? 'upload/'. $this->images->first()->url: 'upload/product_default.jpg');
    }

    public function getSalePriceAttribute()
    {
        return $this->attributes['sale'] ?  $this->attributes['price'] - ( $this->attributes['sale'] * 0.01 *  $this->attributes['price']) : 0;
    }

}

app/Http/Controllers/Client/HomeController.php
<?php

namespace App\Http\Controllers\Client;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\Models\Product;
use App\Models\User;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    protected $product;
    public function __construct(Product $product)
    {
        $this->product = $product;
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        $products = $this->product->latest('id')->paginate(12);
        return view('client.home.index', compact('products'));
    }   
    
    public function search(Request $request)
    {
        $searchQuery = $request->input('name');
    
        $products = Product::where('name', 'like', '%' . $searchQuery . '%')->paginate(12);

        
        if ($products->isEmpty()) {
            //return view('client.products.index', compact('products'))->with(['message' => 'Không tìm thấy sản phẩm có tên ' . $searchQuery]);
            session()->flash('message', 'Không tìm thấy sản phẩm có tên: ' .'`'. $searchQuery.'`');
        // Kiểm tra xem session 'message' đã được thiết lập hay chưa
           // dd(session()->get('message'));
            return view('client.home.index', compact('products'));
        } else {
            return view('client.home.index', compact('products'));
        }
    }
}

app/Http/Controllers/Client/OrderController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Order;
use Illuminate\Http\Request;

class OrderController extends Controller
{

    protected $order;

    public function __construct(Order $order)
    {
        $this->order = $order;
    }
    public function index()
    {
        $orders = $this->order->getWithPaginateBy(auth()->user()->id);
        return view('client.orders.index', compact('orders'));
    }
    public function cancel($id)
    {
        $orders = $this->order->findOrFail($id);
        $orders->update(['status' => 'Cancel']);
        return redirect()->route('client.orders.index')->with(['message'=>'Cancel success']);
    }
}

app/Http/Controllers/Client/ProductController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Models\Product;
use Illuminate\Http\Request;

class ProductController extends Controller
{


    protected $product;
    public function __construct(Product $product)
    {
        $this->product = $product;
    }
    /**
     * Display a listing of the resource.
     */
    public function index(Request $request, $category_id)
    {
        $products =  $this->product->getBy($request->all(), $category_id);
        return view('client.products.index', compact('products'));
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     */
    public function show(string $id)
    {
        $products =  $this->product->with('details')->findOrFail($id);
        return view('client.products.detail', compact('products'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(string $id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, string $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(string $id)
    {
        //
    }
    public function searchByName(Request $request)
    {
        $searchQuery = $request->input('name');
    
        $products = Product::where('name', 'like', '%' . $searchQuery . '%')->paginate(9);

        
        if ($products->isEmpty()) {
            //return view('client.products.index', compact('products'))->with(['message' => 'Không tìm thấy sản phẩm có tên ' . $searchQuery]);
            session()->flash('message', 'Không tìm thấy sản phẩm có tên: ' .'`'. $searchQuery.'`');
        // Kiểm tra xem session 'message' đã được thiết lập hay chưa
           // dd(session()->get('message'));
            return view('client.products.index', compact('products'));
        } else {
            return view('client.products.index', compact('products'));
        }
    }
}

app/Http/Controllers/Client/ProfileController.php
<?php

namespace App\Http\Controllers\Client;

use App\Http\Controllers\Controller;
use App\Http\Requests\Users\UpdateUserRequest;
use Illuminate\Http\Request;
use App\Models\User;
use Illuminate\Support\Facades\Hash;

class ProfileController extends Controller
{   
    protected $user;
    public function __construct(User $user){
        $this->user = $user; 

    }
    public function showAccount(){
        $user = $this->user ->findOrFail(auth()->user()->id);
        $roles = $user->roles;
        //dd($role);
        return view('client.user.index',compact('user','roles'));
    
    }
    public function viewUpdateProfile(){
        $user = User::findOrFail(auth()->user()->id);
        return view('client.user.edit',compact('user'));
    }
    public function UpdateProfile(UpdateUserRequest $request){
        $dataUpdate = $request->except('password');
        $user = $this->user->findOrFail(auth()->user()->id);
        if ($request->password) {
            $dataUpdate['password']= Hash::make($request->password);
        }
        $currentImage = $user->images ? ($user->images->first() ? $user->images->first()->url : asset('upload/default.png')) :asset('upload/default.png');

        $dataUpdate['image'] = $this->user->updateImage($request, $currentImage);
       
        $user->update($dataUpdate);
        $user->images()->delete();
        $user->images()->Create(['url' => $dataUpdate['image']]);
        //dd($dataUpdate);
        return redirect()->route('client.home.account')->with(['message'=>'Update profile success']);
    }
}

resources/views/client/carts/index.blade.php
<!-- Page Header Start -->
@extends('client.layouts.app')
@section('title', 'Cart')
@section('content')
    <div class="row ">
        <div class="d-inline-flex" style="margin-left:40px">
            <p class="m-0"><a href="{{ route('client.home')}}">Home</a></p>
            <p class="m-0 px-2">/</p>
            <p class="m-0">Cart</p>
        </div>
    </div>
        <div class="row px-xl-5">
            <div class="col-lg-12">
            @if (session('message'))
              <div class="row">
                  <h3 class="text-danger">{{ session('message') }}</h3>
              </div>
            @endif
            </div>
            <!-- Shop Product Start -->                            
            <div class="col-lg-8 table-responsive mb-5">
                <table class="table table-bordered text-center mb-0">
                    <thead class="bg-secondary text-dark">
                        <tr>
                            <th>Products</th>
                            <th>Price</th>
                            <th>Size</th>
                            <th>Sale</th>
                            <th>Quantity</th>
                            <th>Total</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody class="align-middle">
                        @foreach ($cart->products as $item)
                        <tr id="row-{{$item->id}}">
                              
                            <td class="align-middle"><img src="{{$item->product->image_path}}" alt=""
                                    style="width: 50px;">{{$item->product->name}}</td>
                            <td class="align-middle">
                                <p
                                    style="{{ $item->product->sale ? 'text-decoration: line-through' : '' }};">
                                    {{ $item->product->price }}VNĐ
                                </p>
                                @if ($item->product->sale)
                                    <p
                                        style="">
                                        {{ $item->product->sale_price }}VNĐ
                                    </p>
                                @endif
                            </td>
                            <td class="align-middle">{{ $item->product_size }}</td>
                            <td class="align-middle">{{ $item->product->sale }}%</td>
                            <td class="align-middle">
                                <div class="input-group quantity mx-auto" style="width: 100px;">
                                    <div class="input-group-btn">  
                                            
                                        <button class="btn btn-sm btn-primary btn-minus btn-update-quantity"
                                            data-action="{{ route('client.carts.update_product_quantity', $item->id) }}"
                                            data-id="{{ $item->id }}">
                                            <i class="fa fa-minus"></i>
                                        </button>
                                    </div>
                                    <input type="number" class="form-control form-control-sm bg-secondary text-center p-0"
                                        id="productQuantityInput-{{ $item->id }}" min="1"
                                        value="{{ $item->product_quantity }}">
                                    <div class="input-group-btn">
                                        <button class="btn btn-sm btn-primary btn-plus btn-update-quantity"
                                            data-action="{{ route('client.carts.update_product_quantity', $item->id) }}"
                                            data-id="{{ $item->id }}">
                                            <i class="fa fa-plus"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td class="align-middle">
                                <span
                                    id="cartProductPrice{{ $item->id }}">{{ $item->product->sale ? $item->product->sale_price * $item->product_quantity : $item->product->price * $item->product_quantity }}VNĐ</span>

                            </td>
                            <td class="align-middle">
                                <button class="btn btn-sm btn-primary btn-remove-product"
                                    data-action="{{route('client.carts.remove_product',$item->id)}}"><i
                                        class="fa fa-times"></i></button>
                            </td>
                        </tr>
                        
                        @endforeach
                        
                    </tbody>
                </table>
                
            </div>
           
            <div class="col-lg-4">
                <form class="mb-5" method="POST" action="{{ route('client.carts.apply_coupon') }}">
                    @csrf
                    <div class="input-group">
                        <input type="text" class="form-control p-4" value="{{ Session::get('coupon_code') }}"
                            name="coupon_code" placeholder="Coupon Code">
                        <div class="input-group-append">
                            <button class="btn btn-primary">Apply Coupon</button>
                        </div>
                    </div>
                </form>
                <div class="card border-secondary mb-5">
                    <div class="card-header bg-secondary border-0">
                        <h4 class="font-weight-semi-bold m-0">Cart Summary</h4>
                    </div>
                    <div class="card-body">
                        <div class="d-flex justify-content-between mb-3 pt-1">
                            <h6 class="font-weight-medium">Subtotal</h6>
                            <h6 class="font-weight-medium total-price" 
                            data-price="{{ $cart->total_price }}VNĐ">
                                {{ $cart->total_price }}VNĐ</h6>
                        </div>
    
    
                        @if (session('discount_amount_price'))
                            <div class="d-flex justify-content-between">
                                <h6 class="font-weight-medium">Coupon </h6>
                                <h6 class="font-weight-medium coupon-div"
                                    data-price="{{ session('discount_amount_price') }}">
                                    {{ session('discount_amount_price') }} VNĐ</h6>
                            </div>
                        @endif
    
                    </div>
                    <div class="card-footer border-secondary bg-transparent">
                        <div class="d-flex justify-content-between mt-2">
                            <h5 class="font-weight-bold">Total</h5>
                            <h5 class="font-weight-bold total-price-all"></h5>
                        </div>
                        <a href="{{route('client.checkout.index')}}" class="btn btn-block btn-primary my-3 py-3">Proceed
                            To Checkout</a>
                    </div>                   
                </div>          
            </div>
        </div>          
            <!-- Shop Product End -->
            
    <!-- Shop End -->
@endsection
@section('script')
        <script src="{{ asset('client/cart/cart.js') }}"></script>
@endsection